version: "3.8"

services:
  imo2tun-frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: $IMAGE_TAG
    container_name: imo2tun-frontend-prod
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - imo2tun-network-prod

networks:
  imo2tun-network-prod:
    driver: bridge